Bandit test data
Eppo-exp/sdk-test-data pull request #20
Opened 2024-05-28 22:48 UTC by schmit

Adding the first version of test data for the bandit

2024-05-28 22:49 UTC, schmit commented on ufc/bandit-flags-v1.json
> +{
This file holds the flag config

2024-05-28 22:49 UTC, schmit commented on ufc/bandit-flags-v1.json
> +      "banner_bandit_flag_uk_only": {
Same as above but filtering for UK users only to test the filtering of flags

2024-05-28 22:49 UTC, schmit commented on ufc/bandit-models-v1.json
> +{
This file contains the bandit configurations

2024-05-29 21:21 UTC, giorgiomartini0 approved these changes

2024-05-29 21:21 UTC, giorgiomartini0 commented on ufc/bandit-tests/test-case-non-bandit-integer-flag.json
Just to double check: is this file meant to be identical to `ufc/bandit-tests/test-case-non-bandit-flag.json`, other than the flag name?

2024-05-29 21:43 UTC, aarsilv requested changes
This is a great start! I have spotted one inconsistency with the UFC to be looked at and then I have some confusion on where "control" is coming from.

2024-05-29 21:43 UTC, aarsilv commented on ufc/bandit-tests/test-case-bandit-does-not-exist.json
> +        "assignment": {"variation": "default", "action": null}
Having an assignment with a variation and action component is breaking from our composite (dynamic variant value) approach. Happy to proceed this way--as its a step towards detailed return objects--but it's a pretty big change.

2024-05-29 22:32 UTC, schmit commented on ufc/bandit-models-v1.json
> +        "coefficients": {
Oh good catch, yes I think we want to have this as a map instead of an array for fast look-ups

2024-05-29 22:33 UTC, schmit commented on ufc/bandit-tests/test-case-banner-bandit-uk-only.json
> +        "assignment": {"variation": "control", "action": null}
`banner_bandit_flag_uk_only` has a variation `control` that is getting assigned since `alice` is not from the `UK`

2024-05-29 22:34 UTC, schmit commented on ufc/bandit-tests/test-case-banner-bandit-uk-only.json
> +        "assignment": {"variation": "control", "action": null}
See: 
https://github.com/Eppo-exp/sdk-test-data/pull/20/files/0518a61d3febc193703e914eb322654cb5178370#diff-a1e2f542e8990b378f18f9b6af91cd397186b764891ae27ccea74d8dfa82d3eeR137

2024-05-29 23:32 UTC, schmit commented on ufc/bandit-tests/test-case-bandit-does-not-exist.json
> +    "flag": "flag_does_not_exist",
That's why it is called "flag does not exist" :) want to make sure that when the flag does not exist, the call to bandit_action still works.

Agreed that having a cold-start bandit test case is useful too!

2024-05-30 00:02 UTC, aarsilv approved these changes
Thanks for addressing my concerns!

2024-05-30 04:28 UTC, merged